module.exports = [
  { url: 'http://mattdesl.github.io/codevember/1.html',
  name: 'Feather', description: 'Canvas 2D particle physics', mobile: true },
  { url: 'http://mattdesl.github.io/codevember/2.html', name: 'Pollock', description: 'Ink splatter effect', mobile: true },
  { url: 'http://mattdesl.github.io/codevember/3.html', name: 'Wave', description: '3D audio visualizer', audio: true },
  { url: 'http://glslb.in/s/dadc0eb1', name: 'GLSL Sketch' },
  { url: 'http://mattdesl.github.io/codevember/5.html', name: 'Displace', description: 'Displacement shader', mobile: true },
  { url: 'http://mattdesl.github.io/codevember/6.html', name: 'Binaural', description: 'Binaural and reverb audio effects', audio: true, mobile: true },
  { url: 'http://mattdesl.github.io/codevember/7.html', name: 'Reactor', description: 'Procedural 3D scene', mobile: true },
  { url: 'http://mattdesl.github.io/codevember/8.html', name: 'Beatgrid', description: 'Audio beat detection', audio: true },
  { url: 'http://mattdesl.github.io/codevember/9.html', name: 'Junk Pile', description: 'Generative canvas 2D rendering', mobile: true },
  { url: 'http://glslb.in/s/40bb7029', name: 'GLSL Sketch' },
  { url: 'http://mattdesl.github.io/codevember/11.html', name: 'Poppies', description: 'Abstract poppy field', mobile: true },
  { url: 'http://glslb.in/s/9ad772d2', name: 'GLSL Sketch' },
  { url: 'http://mattdesl.github.io/codevember/13.html', name: 'Party', description: 'Audio visualizer', audio: true },
  { url: 'http://mattdesl.github.io/codevember/14.html', name: 'Laser Show', description: '3D laser shaders', mobile: true },
  { url: 'http://mattdesl.github.io/codevember/15.html', name: 'Snowden', description: 'Quantized mesh with line rendering' },
  { url: 'http://mattdesl.github.io/codevember/16.html', name: 'Radio', description: 'VU meter reacting to a podcast in real-time', audio: true },
  { url: 'http://mattdesl.github.io/codevember/17.html', name: 'Mr cthulhu', description: 'stringy sphere', mobile: true },
  { url: 'http://codepen.io/mattdesl/full/avMYMd/', name: 'Geometric', description: 'procedural 2D geometric shapes', mobile: true },
  { url: 'http://mattdesl.github.io/codevember/19.html', name: 'AST', description: 'a self-visualizing program' },
  { url: 'http://mattdesl.github.io/codevember/20.html', name: 'Polygraph', description: 'lines on paper', mobile: true },
  { url: 'http://mattdesl.github.io/codevember/21.html', name: 'Silk', description: '3D audio visualizer with screen-space projected lines', audio: true },
  { url: 'http://mattdesl.github.io/codevember/22.html', name: 'Punched', description: 'Encoding text into stylized punched card graphics', mobile: true },
  { url: 'http://mattdesl.github.io/codevember/23.html', name: 'Marvel', description: 'Random set of overlapping Marvel character names' },
  { url: 'http://jam3.github.io/web-audio-player/', name: 'web-audio-player', description: 'An open-source WebAudio library', mobile: true, audio: true },
  { url: 'http://glslb.in/s/fe9a73e2', name: 'GLSL Sketch' },
  { url: 'http://mattdesl.github.io/codevember/26.html', name: 'Streets', description: 'StreetView with 3D environment-mapped text', mobile: true },
  { url: 'http://mattdesl.github.io/codevember/27.html', name: 'Orb', description: 'Abstract design with screen-space projected lines', mobile: true },
  { url: 'http://mattdesl.github.io/codevember/28.html', name: 'Physical', description: 'Exploring mipmap bias for PBR materials', mobile: true },
  { url: 'http://mattdesl.github.io/codevember/29.html', name: 'Disco', description: 'Encoding HDR files as RGBM', mobile: true },
  { url: 'http://mattdesl.github.io/codevember/30.html', name: 'Space', description: '3D audio visualizer', audio: true, mobile: true }
]
